[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "zinq"
authors = [{name = "tjira", email = "tom.jira@gmail.com"}]
description = "Implementations of electronic structure methods and mathematical algorithms in Zig, focusing on clarity, simplicity, and modern system programming."
readme = "README.md"
dynamic = ["version"]

[project.scripts]
zinq = "zinq.launch:main"
eigh = "zinq.launch:eigh"
hf = "zinq.launch:hf"
molint = "zinq.launch:molint"
mp2 = "zinq.launch:mp2"
primecheck = "zinq.launch:primecheck"
primefact = "zinq.launch:primefact"
primegen = "zinq.launch:primegen"
plot = "zinq.plot:main"

[project.urls]
"Homepage" = "https://tjira.github.io/zinq/"
"Bug Tracker" = "https://github.com/tjira/zinq/issues"

[tool.setuptools]
include-package-data = false

[tool.setuptools.package-data]
"zinq" = ["bin/*"]
